services:
  workerapi:
    image: workerapi
    build:
      context: .
      dockerfile: src/WorkerApi/Dockerfile
    deploy:
      mode: replicated
      replicas: 6
    networks:
      - loadbalancing
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: p@55w0rd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - loadbalancing
  nginx:
    build:
      context: .
      dockerfile: src/nginxlb/Dockerfile
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - workerapi   
      
networks:
  loadbalancing: